name: twentyminute
description: A "no interrupts" Twenty Minute Timer

# Do not remove the following line
publish_to: 'none' # Will publish to pub.dev if removed

version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter


  adaptive_theme: ^3.0.0
  animated_text_kit: ^4.2.1
  bitsdojo_window: ^0.1.2
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_vibrate: ^1.3.0
  get: ^4.6.1
  hive: ^2.0.4
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  launch_at_startup: ^0.1.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  shared_preferences: ^2.0.11
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.0.2+1
  wave: ^0.2.0
  window_manager: ^0.2.3

  cv:

  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_sqflite
      ref: dart2_3
      version: '>=0.4.2'

  # Call platformInit() to work with Windows and Linux
  tekartik_app_platform:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_platform
    version: '>=0.1.0'

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.11.1'

  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  bloc_test: ^9.0.1
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/

  fonts:
   - family: Tallymarks
     fonts:
       - asset: assets/fonts/Tallymarks-Regular.otf
